services:
  # Backend API
  - type: web
    name: sistemagestionagricola
    env: node
    region: oregon
    plan: starter
    rootDir: server
    buildCommand: npm install && npx prisma generate && npx prisma db push
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: CORS_ORIGIN
        value: https://sistemagestionagricola-frontend.onrender.com
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: PRISMA_HIDE_UPDATE_MESSAGE
        value: true
      - key: CHECKPOINT_DISABLE
        value: 1
    autoDeploy: true

  # Frontend App
  - type: web
    name: sistemagestionagricola-frontend
    env: static
    region: oregon
    plan: free
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://sistemagestionagricola.onrender.com/api
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
      - path: /assets/*
        name: Cache-Control
        value: max-age=31536000
    redirects:
      - source: /*
        destination: /index.html
        type: rewrite
    autoDeploy: true
