services:
  - type: web
    name: sistemagestionagricola-api
    env: node
    region: oregon
    plan: starter
    rootDir: ./server
    buildCommand: npm install && npx prisma generate && npx prisma db push --accept-data-loss
    startCommand: npx prisma migrate deploy && npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: CORS_ORIGIN
        value: https://sistemagestionagricola.onrender.com,https://sistemagestionagricola-frontend.onrender.com
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: PRISMA_HIDE_UPDATE_MESSAGE
        value: true
      - key: CHECKPOINT_DISABLE
        value: 1
    autoDeploy: true
  - type: web
    name: sistemagestionagricola
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    rootDir: ./client
    envVars:
      - key: VITE_API_URL
        value: https://sistemagestionagricola-api.onrender.com/api
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
      - path: /assets/*
        name: Cache-Control
        value: max-age=31536000
      - path: /site.webmanifest
        name: Content-Type
        value: application/manifest+json; charset=utf-8
    redirects:
      - source: /favicon.ico
        destination: /favicon-elorza.ico
        type: 200
      # SPA catch-all: enviar cualquier ruta desconocida a index.html
      - source: /*
        destination: /index.html
        type: 200
    autoDeploy: true
